name: microservice_dashboard_backend
description: A Dart HTTP backend for the Microservice Status Dashboard
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

# Using built-in dart:io HTTP server instead of shelf for simplicity
# dependencies:
#   shelf: ^1.4.0
#   shelf_router: ^1.1.0

dev_dependencies:
  lints: ^3.0.0

executables:
  server: server
