name: microservice_dashboard_backend
description: A Dart Shelf backend for the Microservice Status Dashboard
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^3.0.0
